### PR TITLE
Plotting vignette

### PR DESCRIPTION
**Pull request by JeffreyCHoover**
I have the first draft written for this vignette. I will attempt to get the Github checks passing before sending for your review.

### CODE REVIEW

**Comment by JeffreyCHoover** [comment]
@wjakethompson   with all of the various projects going on at the moment, I know this is low priority, but the plotting vignette is ready for your content review. All of the github checks at least passed without the headache of last time!

**Comment by wjakethompson** [comment]
@JeffreyCHoover I took a pass to reorganized and change how the plots were defined (i.e., use `scale_color_atlas()` rather than `scale_color_discrete(palette = palette_atlas)`). Please take a pass to proof/suggest any changes!

**Comment by wjakethompson** [comment]
@JeffreyCHoover I need to go back through and resolve some merge conflicts, but have you had a chance to look at the content to see if you have any recommended changes?

**Comment by JeffreyCHoover** [comment]
@wjakethompson I did. Sorry it took me so long to get them pushed onto here! I had a few small wording/grammatical recommendations. Nothing major.

**Comment by wjakethompson** [comment]
I'm not too worried about it. Looks like just some issues with dependencies not loading correctly on R-devel. Once those packages are fixed downstream, this should be fine. I'm going to go ahead and merge this.

Closes #12.

**Pull request merged**
